name: instance

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Files
        uses: actions/checkout@v3
      
      - name: ssh deploy
        # You may pin to the exact commit or the version.
        # uses: easingthemes/ssh-deploy@3884c8554ff45c0fd37d3f12a76288d06ce7a2ff
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          # Private key part of an SSH key pair
          SSH_PRIVATE_KEY:  ${{secrets.AWS_SSH_KEY}}
          REMOTE_HOST: ${{secrets.AMAZON_HOST}}
          REMOTE_USER: ${{secrets.AMAZON_USER}}
          SOURCE: ./
          # Target directory
          TARGET:  ${{secrets.AMAZON_TARGET}}
          SCRIPT_BEFORE: |
            echo "------------------ BEFORE -----------------"
            cd instance
            sudo docker-compose down
            ls
            echo "------------------ BEFORE -----------------"
          SCRIPT_AFTER: |
            echo "------------------ AFTER -----------------"
            cd instance
            sudo docker-compose up --build -d
            echo "------------------ AFTER -----------------"
        
    
    

